### ISSUE TITLE
Error when install payara on eclipse

### ISSUE THREAD

**Issue by techyosa** [payara/Payara_PatchedProjects#141]
Unable to read repository at https://raw.githubusercontent.com/payara/Payara_PatchedProjects/eclipse/payaratools/oxygen/development/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by gnumarco** [comment]
Hi. I cannot find where to use -Djavax.net.ssl.trustStore=/path/to/jdk/jre/lib/security/cacerts
I have this error since a few days, and I am unable to solve it...
